<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="BLR2-5CG1327HQ2" failures="2" tests="11" name="Default test" time="59.899" errors="0" timestamp="2023-06-03T22:46:07 IST">
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.6"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.652"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.596"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.584"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.576"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.588"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.664"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.59"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithValidCredential" time="0.747"/>
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithInvalidCredential" time="0.479">
    <failure type="java.lang.AssertionError" message="Assertion Faile at void TestCase.Login_Test.verifyLoginWithInvalidCredential(java.lang.reflect.Method) expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assertion Faile at void TestCase.Login_Test.verifyLoginWithInvalidCredential(java.lang.reflect.Method) expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Utility.Utilise1.VerificationAssertion(Utilise1.java:67)
at TestCase.Login_Test.verifyLoginWithInvalidCredential(Login_Test.java:50)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithInvalidCredential -->
  <testcase classname="TestCase.Login_Test" name="verifyLoginWithoutCredential" time="0.305">
    <failure type="java.lang.AssertionError" message="Assertion Faile at void TestCase.Login_Test.verifyLoginWithoutCredential(java.lang.reflect.Method) expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assertion Faile at void TestCase.Login_Test.verifyLoginWithoutCredential(java.lang.reflect.Method) expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at Utility.Utilise1.VerificationAssertion(Utilise1.java:67)
at TestCase.Login_Test.verifyLoginWithoutCredential(Login_Test.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verifyLoginWithoutCredential -->
</testsuite> <!-- Default test -->
